#!/bin/zsh
set -euo pipefail

# Create a timestamped, fillable physical TestFlight QA record. The output is
# ignored by git so tester/device details do not accidentally land in the repo.

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
TEMPLATE="$ROOT_DIR/docs/HARDWARE_QA_RECORD_TEMPLATE.md"
OUTPUT_ROOT="$ROOT_DIR/.build/hardware-qa-records"

scenario="${1:-manual}"
build_number="${2:-unknown-build}"
timestamp="$(date +%Y%m%d-%H%M%S)"
safe_scenario="$(echo "$scenario" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//')"
safe_build="$(echo "$build_number" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9._-]+/-/g; s/^-+//; s/-+$//')"
output_dir="$OUTPUT_ROOT/$timestamp"
output_file="$output_dir/${safe_scenario:-manual}_${safe_build:-unknown-build}.md"

if [[ ! -f "$TEMPLATE" ]]; then
    echo "Missing template: $TEMPLATE"
    exit 1
fi

mkdir -p "$output_dir"
cp "$TEMPLATE" "$output_file"

cat >> "$output_file" <<EOF

---

Generated by \`scripts/new-hardware-qa-record.sh\`.

Suggested scenario: $scenario
Suggested build number: $build_number
EOF

echo "Created hardware QA record:"
echo "$output_file"
