#!/bin/zsh
set -euo pipefail

# Create a timestamped, fillable physical TestFlight QA record. The output is
# ignored by git so tester/device details do not accidentally land in the repo.

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
TEMPLATE="$ROOT_DIR/docs/HARDWARE_QA_RECORD_TEMPLATE.md"
OUTPUT_ROOT="$ROOT_DIR/.build/hardware-qa-records"

scenario="${1:-manual}"
build_number="${2:-unknown-build}"
timestamp="$(date +%Y%m%d-%H%M%S)"
record_date="$(date +%Y-%m-%d)"
safe_scenario="$(echo "$scenario" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//')"
safe_build="$(echo "$build_number" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9._-]+/-/g; s/^-+//; s/-+$//')"
output_dir="$OUTPUT_ROOT/$timestamp"
output_file="$output_dir/${safe_scenario:-manual}_${safe_build:-unknown-build}.md"
git_commit="$(git -C "$ROOT_DIR" rev-parse --short HEAD 2>/dev/null || echo "unknown")"
tester_name="$(git -C "$ROOT_DIR" config user.name 2>/dev/null || true)"
tester_name="${tester_name:-${USER:-}}"
latest_simulator_summary="$(find "$ROOT_DIR/.build/qa-simulator-seeds" -path "*/summary.md" -type f -print 2>/dev/null | sort | tail -n 1)"
if [[ -n "$latest_simulator_summary" ]]; then
    latest_simulator_summary="${latest_simulator_summary#$ROOT_DIR/}"
else
    latest_simulator_summary="not generated yet"
fi

case "$safe_scenario" in
    same-phone)
        scenario_label="Same phone"
        ;;
    child-ipad)
        scenario_label="Child iPad"
        ;;
    child-iphone)
        scenario_label="Child iPhone"
        ;;
    *)
        scenario_label="$scenario"
        ;;
esac

if [[ ! -f "$TEMPLATE" ]]; then
    echo "Missing template: $TEMPLATE"
    exit 1
fi

mkdir -p "$output_dir"
cp "$TEMPLATE" "$output_file"

replace_row() {
    local field="$1"
    local value="$2"
    local tmp_file="$output_file.tmp"

    awk -v field="$field" -v value="$value" '
        BEGIN { FS = OFS = "|" }
        {
            label = $2
            gsub(/^[[:space:]]+|[[:space:]]+$/, "", label)
            if (label == field && NF >= 3) {
                $3 = " " value " "
            }
            print
        }
    ' "$output_file" > "$tmp_file"
    mv "$tmp_file" "$output_file"
}

replace_row "Build number" "$build_number"
replace_row "Git commit" "$git_commit"
replace_row "Tester" "$tester_name"
replace_row "Date" "$record_date"
replace_row "Scenario" "$scenario_label"
replace_row "Latest simulator QA summary" "$latest_simulator_summary"

cat >> "$output_file" <<EOF

---

Generated by \`scripts/new-hardware-qa-record.sh\`.

This file is ignored by git. Fill the remaining blanks while testing the
TestFlight build, and keep any screen recordings or screenshots with the same
scenario/build label.
EOF

echo "Created hardware QA record:"
echo "$output_file"
